### ISSUE TITLE
authenticated blows up....

### ISSUE THREAD

**Issue by timmeade** [perkinsjr/nextjs-with-firebase-main#2]
First wanted to say one of the best tutorials i've seen in quite a while.

I updated local code to new chakra/react instead of current chakra/core.   Seems to work fine until:

authenticated =>. logout.     Blows up most spectacular.  

```
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:277:15)
    at ServerResponse.setHeader (node:_http_outgoing:563:11)
    at DevServer.sendHTML (/Users/tim/src/active/max-base-app/node_modules/next/dist/server/next-dev-server.js:37:5)
    at DevServer.render (/Users/tim/src/active/max-base-app/node_modules/next/dist/next-server/server/next-server.js:76:37)
    at async Object.fn (/Users/tim/src/active/max-base-app/node_modules/next/dist/next-server/server/next-server.js:48:704)
    at async Router.execute (/Users/tim/src/active/max-base-app/node_modules/next/dist/next-server/server/router.js:25:67)
    at async DevServer.run (/Users/tim/src/active/max-base-app/node_modules/next/dist/next-server/server/next-server.js:68:1042)
    at async DevServer.handleRequest (/Users/tim/src/active/max-base-app/node_modules/next/dist/next-server/server/next-server.js:32:504) {
  code: 'ERR_HTTP_HEADERS_SENT'
}
node:events:306
      throw er; // Unhandled 'error' event
      ^

Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at new NodeError (node:internal/errors:277:15)
    at write_ (node:_http_outgoing:717:11)
    at ServerResponse.end (node:_http_outgoing:817:5)
    at ServerResponse.end (/Users/tim/src/active/max-base-app/node_modules/next/dist/compiled/compression/index.js:1:141519)
    at DevServer.handleRequest (/Users/tim/src/active/max-base-app/node_modules/next/dist/next-server/server/next-server.js:32:624)
Emitted 'error' event on ServerResponse instance at:
    at emitErrorNt (node:_http_outgoing:695:9)
    at processTicksAndRejections (node:internal/process/task_queues:81:21) {
  code: 'ERR_STREAM_WRITE_AFTER_END'
}
```

Just FYI.   I'm working on it now.....

**Comment by perkinsjr** [comment]
I cannot recreate this issue with the current code. That usually means you are trying to set headers twice, in the code I don't set the headers but redirect to /

**Comment by timmeade** [comment]
changing the getServerSideProps in authenticated seems to fix.  I am on next 11 btw.  

export async function getServerSideProps(context) {
  try {
    const cookies = nookies.get(context);
    const token = await verifyIdToken(cookies.token);
    const { uid, email } = token;
    return {
      props: { session: `Your email is ${email} and your UID is ${uid}.` },
    };
  } catch (err) {
    return {
      redirect: {
        destination: '/auth/login',
        permanent: false,
      },
    };
  }
}
export default Authenticated;

**Comment by perkinsjr** [comment]
Even on Next 11 with zero changes from this code base I get no errors. You have changed more of the code base as you show this:

redirect: {
        destination: '/auth/login',
        permanent: false,
      },
    };
       
When all of the code is found directly in the pages directory.

**Comment by timmeade** [comment]
Maybe that was it.  I am using some folders.    It hit from the very first. i copied raw pages out of your repo.    Only the fix above kept if from crashing.

**Comment by perkinsjr** [comment]
Yup, can't redirect to it. So the headers will error out because it tries to rewrite back to the client twice.
